# Generated by Django 3.0.5 on 2020-08-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_questions',
            name='image',
            field=models.FileField(upload_to='pics/'),
        ),
    ]
