# Generated by Django 3.0.5 on 2020-08-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdb', '0002_auto_20200805_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_questions',
            name='image',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='student_questions',
            name='query',
            field=models.TextField(max_length=800),
        ),
    ]
