# Generated by Django 3.0.5 on 2020-08-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdb', '0004_auto_20200805_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_questions',
            name='upload_on',
            field=models.DateField(auto_now=True),
        ),
    ]
